#!/usr/bin/env bash

# bundle install
docker run -t --rm \
  -v $(pwd):/app \
  ruby:3.2-slim-bullseye \
  /bin/bash -c 'apt-get update -qq && apt-get install -y --no-install-recommends build-essential git make && cd /app && gem install bundler && bundle install --jobs 3; echo "LOCK_FILE_UPDATE_EXIT_CODE=$?"'

# Update Changelog
docker run -t --rm -e CHANGELOG_GITHUB_TOKEN -v $(pwd):/usr/local/src/your-app \
  githubchangeloggenerator/github-changelog-generator:1.16.2 \
  github_changelog_generator --future-release $(grep STRING lib/beaker-abs/version.rb |rev |cut -d "'" -f2 |rev)
